import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { db } from '@/lib/db';
import { users, sessions, accounts, verifications, tenants } from '@/lib/db/schema';

/**
 * Better Auth — self-hosted, sessions live in our own Postgres.
 *
 * The user model is mapped onto the existing `users` table rather than a
 * separate auth table, so there is one identity per person and the 15 FKs
 * that already reference `users.id` keep working untouched.
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: 'pg',
    // Keys must match the modelName configured for each model below, not Better
    // Auth's default singular names.
    schema: { users, sessions, accounts, verifications },
  }),

  // IDs are generated by Better Auth as UUIDs so they fit the uuid columns
  // these tables already use.
  advanced: {
    database: {
      generateId: 'uuid',
    },
  },

  emailAndPassword: {
    enabled: true,
  },

  databaseHooks: {
    user: {
      create: {
        // users.tenantId is NOT NULL, but Better Auth's sign-up payload has no
        // concept of a tenant. This deployment serves one studio, so new
        // accounts join the existing tenant. Sign-up is not publicly reachable
        // (see the /api/auth/sign-up block in proxy.ts).
        //
        // NOTE: today the only caller is /api/v1/setup. The employees module
        // inserts straight into `users` and never creates an `accounts` row, so
        // staff created there cannot sign in (hasLogin is false for them).
        // Giving employees credentials is still outstanding.
        before: async (user) => {
          const record = user as typeof user & { tenantId?: string };
          if (record.tenantId) return { data: user };

          const [tenant] = await db.select({ id: tenants.id }).from(tenants).limit(1);
          if (!tenant) {
            throw new Error('Cannot create a user before a tenant exists.');
          }
          return { data: { ...user, tenantId: tenant.id } };
        },
      },
    },
  },

  user: {
    modelName: 'users',
    fields: {
      name: 'fullName',
      image: 'photoUrl',
    },
    additionalFields: {
      // input: false keeps these out of any request body, so nothing
      // web-facing can assign itself a tenant or escalate its own role.
      // required: false because Better Auth validates the payload before the
      // create hook runs, and the hook is what supplies tenantId. The NOT NULL
      // constraint on users.tenant_id is the actual guarantee.
      tenantId: { type: 'string', required: false, input: false },
      role: { type: 'string', required: false, defaultValue: 'designer', input: false },
    },
  },

  session: {
    modelName: 'sessions',
    expiresIn: 60 * 60 * 24 * 7, // 7 days
    updateAge: 60 * 60 * 24,     // refresh once a day
  },

  account: { modelName: 'accounts' },
  verification: { modelName: 'verifications' },
});
